import 'package:freezed_annotation/freezed_annotation.dart';

part 'bank_account.g.dart';
part "bank_account.freezed.dart";

@freezed
class BankAccountDetails with _$BankAccountDetails {
  const factory BankAccountDetails({
    required String bank,
    required String branchCode,
    required num accountNumber,
  }) = _BankAccountDetails;

  factory BankAccountDetails.fromJson(Map<String, dynamic> json) =>
      _$BankAccountDetailsFromJson(json);

  // toJson & copyWith functionality (is generated by freezed)
}
