// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrXFvdIt0Z8qzdvl_TDr_w3a3_-XzEh2A',
    appId: '1:225962385955:web:d07d77c6963c65fa3e8796',
    messagingSenderId: '225962385955',
    projectId: 'crisissurvivors-6f26f',
    authDomain: 'crisissurvivors-6f26f.firebaseapp.com',
    storageBucket: 'crisissurvivors-6f26f.firebasestorage.app',
    measurementId: 'G-EDYTW52SF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV91YU0S-otBMXg8xHfltenKOpXjO3jkU',
    appId: '1:225962385955:android:84e38ecbe93bc3e33e8796',
    messagingSenderId: '225962385955',
    projectId: 'crisissurvivors-6f26f',
    storageBucket: 'crisissurvivors-6f26f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3fXKHvfRXK2-HnilBhBBT1lIp-8YpR7w',
    appId: '1:225962385955:ios:f30f8cc5ca3cde163e8796',
    messagingSenderId: '225962385955',
    projectId: 'crisissurvivors-6f26f',
    storageBucket: 'crisissurvivors-6f26f.firebasestorage.app',
    iosBundleId: 'com.example.crisisSurvivors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3fXKHvfRXK2-HnilBhBBT1lIp-8YpR7w',
    appId: '1:225962385955:ios:f30f8cc5ca3cde163e8796',
    messagingSenderId: '225962385955',
    projectId: 'crisissurvivors-6f26f',
    storageBucket: 'crisissurvivors-6f26f.firebasestorage.app',
    iosBundleId: 'com.example.crisisSurvivors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrXFvdIt0Z8qzdvl_TDr_w3a3_-XzEh2A',
    appId: '1:225962385955:web:a31255b0920a9fd93e8796',
    messagingSenderId: '225962385955',
    projectId: 'crisissurvivors-6f26f',
    authDomain: 'crisissurvivors-6f26f.firebaseapp.com',
    storageBucket: 'crisissurvivors-6f26f.firebasestorage.app',
    measurementId: 'G-85VWBN0T4S',
  );
}
